global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # Later add your backend servers here
  # - job_name: 'my-backend-app'
  #   static_configs:
  #     - targets: ['host.docker.internal:3001']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
