global:
  scrape_interval: 15s

scrape_configs:

  # - job_name: 'alertmanager'
  #   static_configs:
  #     - targets: ['alertmanager:9093']

  # - job_name: 'soulspace-staging-backend'
  #   metrics_path: /metrics
  #   scheme: https
  #   static_configs:
  #     - targets: ['aimetastartsoulspaceserver-production.up.railway.app']
  
  - job_name: 'test node server'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['13.204.42.241:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
